# Generated by Django 4.2.1 on 2023-06-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source", models.URLField(max_length=255)),
                (
                    "prep_time",
                    models.PositiveIntegerField(verbose_name="Czas przygotowania"),
                ),
                (
                    "wait_time",
                    models.PositiveIntegerField(verbose_name="Czas oczekiwania"),
                ),
                (
                    "cook_time",
                    models.PositiveIntegerField(verbose_name="Czas gotowania"),
                ),
                ("servings", models.PositiveIntegerField(verbose_name="Porcje")),
                ("comment", models.TextField(verbose_name="Komentarz")),
                ("calories", models.PositiveIntegerField(verbose_name="Kalorie")),
                ("fat", models.PositiveIntegerField(verbose_name="Tłuszcz")),
                (
                    "satfat",
                    models.PositiveIntegerField(verbose_name="Tłuszcz nasycony"),
                ),
                ("carbs", models.PositiveIntegerField(verbose_name="Węglowodany")),
                ("fiber", models.PositiveIntegerField(verbose_name="Błonnik")),
                ("sugar", models.PositiveIntegerField(verbose_name="Cukier")),
                ("protein", models.PositiveIntegerField(verbose_name="Białko")),
                ("instructions", models.TextField(verbose_name="Instrukcje")),
            ],
            options={
                "verbose_name": "Danie",
                "verbose_name_plural": "Danie",
            },
        ),
        migrations.CreateModel(
            name="RecipeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.recipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tagi",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.recipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Składnik",
                "verbose_name_plural": "Składniki",
            },
        ),
    ]
