# Generated by Django 4.2.1 on 2023-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_globalingredient_recipeingredient_global_ingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalingredient",
            options={
                "verbose_name": "Globalny składnik",
                "verbose_name_plural": "Globalne składniki",
            },
        ),
        migrations.RemoveField(
            model_name="recipetag",
            name="recipe",
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="backend.recipetag", verbose_name="Tagi"),
        ),
    ]
